### ISSUE TITLE
inject should fail if the mirror contains already a higher version

### ISSUE THREAD

**Issue by XSven** [briandfoy/cpan-mini-inject#13]
I was able to inject App-runscript-1.0.0-TRIAL6.tar.gz into my DarkPAN mirror although the mirror already contains App-runscript-1.0.2.tar.gz. This shouldn't be possible!

**Comment by briandfoy** [comment]
Why shouldn't this be possible? It would be a lot of work to have to check every other file to see if the new file  conflicts with it and has an increasing version.

**Comment by XSven** [comment]
It shouldn't be possible because it is **inconsistent** and as an end user I am expecting that a tool like `mcpani` should prevent me from doing "stupid" things on purpose or by accident. I cannot judge how much work it is to implement this now but if it is a lot maybe the reason is a design mistake at the very beginning of the implementation.

**Comment by briandfoy** [comment]
CPAN.pm and cpanm allows you to directly address files in a mirror, and multiple versions of the same modules can co-exist in the mirror. The packages file only translates module names to the file that has the highest version. There are some valid reasons to have older versions in a mirror, especially for mirrors that support many things and at least one of those things can only use the older version.

Are you seeing problems in the packages file when you inject files like this? Can you show what happens in the packages file when you inject both of those modules?

**Comment by XSven** [comment]
That is new to me. I thought the `CPAN::Mini` based mirror would contain only the most recent version of a module. How can I configure how many historical files of a module are kept in the mirror.
I do not see problems. I see pollution because users can do things that shouldn't be possible. If you don't see the need for such a guidance please feel free to close this issue.
