### ISSUE TITLE
mcpani executable no longer installed in bin/ directory

### ISSUE THREAD

**Issue by XSven** [briandfoy/cpan-mini-inject#3]
The `mcpani` executable is no longer installed in the _bin/_ directory.

**Comment by briandfoy** [comment]
Yikes, I left the `EXE_FILES` out of *Makefile.PL*.  There were no code changes to mcpani so the old one should work, but a fix is on the way now. Thanks,

**Comment by briandfoy** [comment]
This should be fixed in 1.003. Thanks,
